title:        CS 6460 Design Portfolio
description:  A quick look at my group project highlights & final-project user-testing + iteration journey
theme:        jekyll-theme-cayman   # built-in; attractive & zero setup
markdown:     kramdown