title:        Your Course Design Portfolio
description:  A quick look at our group project highlights & final-project user-testing journey
theme:        jekyll-theme-cayman   # built-in; attractive & zero setup
markdown:     kramdown